[package]
name = "big-fat-fish-pet"
version = "0.1.0"
description = "蓝色大肥鱼 桌面宠物"
authors = ["you"]
edition = "2021"

[lib]
name = "big_fat_fish_pet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
